version: "{build}"
image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON_EXE: "C:\\Python36-x64\\python.exe"
    - PYTHON_EXE: "C:\\Python37-x64\\python.exe"
    - PYTHON_EXE: "C:\\Python38-x64\\python.exe"
    - PYTHON_EXE: "C:\\Python39-x64\\python.exe"

install:
  - "%PYTHON_EXE% --version"
  - "%PYTHON_EXE% setup.py install"
  - "%PYTHON_EXE% -m pip install pytest"

build: off

test_script:
  - "%PYTHON_EXE% -m pytest"
