name: Install and Test

on: [ workflow_dispatch, pull_request ]

jobs:
  install_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel setuptools_scm build
          python -m build -nwx .
          python -m pip install --upgrade ./dist/*.whl
          python -m pip install pytest
        shell: bash
      - name: Run tests
        run: pytest
      - name: Run CLI
        run: |
          pyspdxtools_parser --file ./tests/data/formats/SPDXJSONExample-v2.3.spdx.json
          pyspdxtools_convertor --infile ./tests/data/formats/SPDXTagExample-v2.3.spdx -o temp.json
